name: main

on:
  pull_request:
  push:
    branches:
      - main

env:
  DOTNET_VERSION: 9.x
  DOTNET_CLI_TELEMETRY_OPTOUT: 1

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      - run: dotnet restore --configfile nuget.config
      - run: dotnet build --no-restore --configuration Release

  pack:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      - run: dotnet pack --configuration Release --output nupkgs
      - run: dotnet push nupkgs/*.nupkg --source https://nuget.pkg.github.com/jterral/index.json --api-key ${{ secrets.NUGET_AUTH_TOKEN }}
