name: main

on:
  pull_request:
  push:
    branches:
      - main

env:
  DOTNET_VERSION: 9.x
  DOTNET_CLI_TELEMETRY_OPTOUT: 1

jobs:
  dotnet-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      - run: dotnet restore --configfile nuget.config
      - run: dotnet build --no-restore --configuration Release
